### ISSUE TITLE
Copy other classes from .xbase.junit into .xbase.testing

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-extras#100]
I think that classes that do not deal with the UI in .xbase.junit should be copied into .xbase.testing, e.g., org.eclipse.xtext.xbase.junit.evaluation.AbstractXbaseEvaluationTest and org.eclipse.xtext.xbase.junit.typesystem.TypeSystemSmokeTester.

This way we can deprecate those classes in .xbase.junit

(related to https://github.com/eclipse/xtext-eclipse/issues/155)

**Comment by spoenemann** [comment]
Fixed with #103.
