### ISSUE TITLE
LongRunningTests ignore -x test

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#101]
LongrunningTests ignore `-x test` from gradle call

**Comment by cdietrich** [comment]
@oehme @spoenemann is it possible to have a if a not then b not? do we want to have that?

**Comment by spoenemann** [comment]
Long running tests have their own task `longrunningTest`. Have you tried `-x longrunningTest`?

**Comment by cdietrich** [comment]
of course that works but everybody who will run it locally will just set -x test cause -x longrunningTest is unexpected => long build times for newbees like me

**Comment by spoenemann** [comment]
If you don't want to run tests, just do `./gradlew assemble` instead of `./gradlew build`. I'm against adding any magic that executes `longrunningTest` only if `test` is active.

**Comment by cdietrich** [comment]
ok then lets close this
