### ISSUE TITLE
[Xbase] Octal Literals: Missing Range Check

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#104]
The Octal Literals miss a range check at model time

```
	def static void main(String[] args) {
		println(019)
	}
```

leads to

```
Java problem: The literal 019 of type int is out of range
```

**Comment by cdietrich** [comment]
alternative viewpoint: we do support octal literals and generate them in a wrong way towards java. @svenefftinge can you comment on this?

**Comment by szarnekow** [comment]
Octal literals are not supported by Xbase / Xtend. See NumberLiterals:

```
public int getBase(XNumberLiteral literal) {
	if (isHex(literal))
		return 16;
	else
		return 10;
}
```

It appears to be a bug in the compilation strategy for number literals.
