### ISSUE TITLE
Build xbase and xtend lib built with Java 6

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-extras#124]
To allow usage of xtend on Java 6 runtimes, we need to make sure the libs are compiled for that.

**Comment by cdietrich** [comment]
@svenefftinge shouldnt that be https://github.com/eclipse/xtext-lib

**Comment by svenefftinge** [comment]
Yes, you are right https://github.com/eclipse/xtext-lib/issues/45
