### ISSUE TITLE
Xbase Test Langs are all broken

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#137]
```
binder.bind(String.class).annotatedWith(Names.named(Constants.FILE_EXTENSIONS)).toInstance("");
```

**Comment by cdietrich** [comment]
cc @spoenemann

**Comment by spoenemann** [comment]
It's a different behavior between the old and new generator. I have set `fileExtensions` explicitly to `""` because that's how it was before. We should just remove those, so the default extensions are created.

**Comment by cdietrich** [comment]
will you do that?
