### ISSUE TITLE
content assist blocked after expression with nested lambdas

### ISSUE THREAD

**Issue by paulluap** [eclipse/xtext-extras#148]
To reproduce, create a simple class
Test.xtend: 
```
class Test{
	def test(Object p1, Object p2){
	}
	def whenOK((Object)=>void p) {		
	}
}
```
then create a test.xbase file with the content: 
```
val t = new Test()
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
t.test(t, t.whenOK[
	
])
])
])
])
])
])
])
])
])
```
press Ctrl + Space to trigger content assist. Then the editor gets stuck. 

The editor only takes about 10 seconds to responde when the code is changed to : 
```
val t = new Test()
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [
t.test(t, [	
])
])
])
])
])
])
])
])
])
```
So it maybe depends on how deep the lambda is nested. 

The problem seems to be in the parser when content assist builds the context. 
see also: https://www.eclipse.org/forums/index.php/t/1086575/

**Comment by cdietrich** [comment]
see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=368908

**Comment by paulluap** [comment]
Is there any possible fix for this ? Or I think I need to build a custom content assist to workaround this? Maybe I can look at xtend's content assist implementation, as the same expression works well in xtend.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
