### ISSUE TITLE
find new home for ClasspathScannerTest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#16]
and the test impl shall be overlooked. imho it should do a `val classloader = new URLClassLoader(#[bootstrapJar.toURI.toURL], null)`

**Comment by spoenemann** [comment]
Where is the test implementation currently?

**Comment by cdietrich** [comment]
it is at dev null but was ./tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.xtend

**Comment by cdietrich** [comment]
@spoenemann @sailingKieler this might be related to the reintroduction of bootstrap.jar

**Comment by cdietrich** [comment]
Fixed in 2.13
