### ISSUE TITLE
JvmModelAssociator removeAssociation does not remove source to jvmElement association

### ISSUE THREAD

**Issue by capacman** [eclipse/xtext-extras#161]
Hi,

JvmModelAssociator removeAssociation does not remove source to jvmelement association. In line 468 of 
 https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java
`targets.remove(sourceElement);`
should be 
`targets.remove(jvmElement);`

**Comment by kthoms** [comment]
How can this be reproduced?

**Comment by cdietrich** [comment]
xtext does not call this. am writing a unit test right now

**Comment by cdietrich** [comment]
fixed in 2.13
