### ISSUE TITLE
Equality test on atomic numbers.

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-extras#186]
In the Java API, the atomic number, e.g. `AtomicInteger` does not provide an implementation of the `equals(Object)` function.

Consider the following Xtend code:
```xtext
def boolean fct1(AtomicInteger a, AtomicInteger b) {
    a == b
}
def boolean fct2(int a, AtomicInteger b) {
    a == b
}
def void main() {
    var int x = 4
    var AtomicInteger y = new AtomicInteger(4)
    var AtomicInteger z = new AtomicInteger(4)
    System.out.println(y + "==" + z + " => " + fct1(y, z))
    System.out.println(x + "==" + y + " => " + fct2(x, y))
}
```

The generated Java code looks like:
```java
public boolean fct1(AtomicInteger a, AtomicInteger b) {
    return Objects.equal(a, b);
}
public boolean fct2(int a, AtomicInteger b) {
    return Objects.equal(Integer.valueOf(a), b);
}
```

The result of the execution of the `main` function display:
```
4 == 4 => false
4 == 4 => false
```
It is not the expected result by me and all my students, since all the tested objects are numbers.

I have solved this issue in my own DSL by writing a specific extensions provider that is implicitly imported with my `ImplicitlyImportedFeatures`.

Nevertheless, I think this may an issue from all the Xbase-based DSLs.
Is is true?
If yes, what is the best way for solving this issue?

**Comment by gallandarakhneorg** [comment]
I have created a collection of extension providers that are giving the operators that I think missed from Xbase: https://github.com/sarl/sarl/tree/0.6.1/main/coreplugins/io.sarl.lang/src/io/sarl/lang/bugfixes/pending/bug764

Among all the extensions, the one related to AtomicInteger may serve as a typical example: https://github.com/sarl/sarl/blob/0.6.1/main/coreplugins/io.sarl.lang/src/io/sarl/lang/bugfixes/pending/bug764/AtomicIntegerExtensions.java

**Comment by cdietrich** [comment]
originating from https://www.eclipse.org/forums/index.php/t/1089278/

**Comment by cdietrich** [comment]
To be discussed: to we want that? what about breaking existing code. what about corner cases mentioned in the forum post by ed.

**Comment by szarnekow** [comment]
The == operator is supposed to be a shortcut for Object.equals. While I can see the value in having comparison operators for different number types, I fear that we overload the semantics of the == in the default case. It would certainly not harm to have an opt-in for these kinds of tests, but doing these by default appears to be undesirable for me.

**Comment by gallandarakhneorg** [comment]
All your comments lead me to the conclusion that adding the proposed method extensions within Xbase may not be a good idea because it does not mimic the Java API specification: AtomicInteger has no equals function defined, then == operator cannot be used on it. I fully understand this design choice.

My expectations related to the == behavior does not mimic these Java API specification. I have a point of view that does not enforce a perfect mapping between my DSL and Java. In the context of my DSL, the semantic of == should works for all subtypes of Number, including AtomicInteger.

Consequently, I would like to propose you to discard my suggestion for Xbase, and close this issue.

For keeping track of the work done, someone who is interested by my == method extensions, takes a look in the [SARL project](https://github.com/sarl/sarl).

**Comment by cdietrich** [comment]
ok so i will close this issue for now
