### ISSUE TITLE
[Xbase] Consider overloaded getTypeForName(String, ITypeComputationState) in XbaseTypeComputer

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#192]
i wonder if we should have an additional getTypeForName(String, ITypeComputationState) in XbaseTypeComputer (see https://www.eclipse.org/forums/index.php/t/1089612/)

**Comment by szarnekow** [comment]
Yes, we should overload the methods that take a Class<?> as first arg in `AbstractTypeComputer`, e.g. `getTypeForName`, `getRawTypeForName` and also `findDeclaredType`

**Comment by cdietrich** [comment]
Fixed in 2.14
