### ISSUE TITLE
Make FeatureScopeTracker instantiable without creating an extra subclass

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#199]

**Comment by kthoms** [comment]
I assume you have a concrete use case?

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/issues/2359
https://github.com/sjka/smarthome/commit/aa35e658ad146ca445798ce860d11da111d9028e
plus something similar in customer project

**Comment by cdietrich** [comment]
Fixed in 2.14
