### ISSUE TITLE
Generated code optimization

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-extras#20]
In my DSL, I have:
```
import io.sarl.C1
agent A {
   def caller {
     getSkill(C1).myfunction(Integer)
     getSkill(C1).myfunction(Float, 1)
     getSkill(C1).myfunction(String, 2, 3)
   }
}
```

The generated Java code is:
```java
import io.sarl.C1;
public class A extends Agent {
  protected void caller() {
    C1 _skill = this.getSkill(C1.class);
    _skill.myfunction(Integer.class);
    C1 _skill_1 = this.getSkill(C1.class);
    _skill_1.myfunction(Float.class, 1);
    C1 _skill_2 = this.getSkill(C1.class);
    _skill_2.myfunction(String.class, 2, 3);
  }
}
```

In the generated code, the three variables `_skill`, `_skill_1`, `_skill_2` are pointing to the same `C1` instance; because there is no `setSkill` call.

Note that `getSkill` is anotated with `@Pure`.

It would be nice if the Xbase expression compiler is able to optmize the generated code in order to obtain:
```java
import io.sarl.C1;
public class A extends Agent {
  protected void caller() {
    C1 _skill = this.getSkill(C1.class);
    _skill.myfunction(Integer.class);
    _skill.myfunction(Float.class, 1);
    _skill.myfunction(String.class, 2, 3);
  }
}
[/code]

Of course, the DSL user may type the following code for obtaining an optimized input code, such as:
```
import io.sarl.C1
agent A {
   def caller {
     val s = getSkill(C1)
     s.myfunction(Integer)
     s.myfunction(Float, 1)
     s.myfunction(String, 2, 3)
   }
}
```
But it depends on the DSL user skills. It would be better if the Xbase expression compiler is able to do some optimization tasks itself.

**Comment by spoenemann** [comment]
I don't think we can solve this in the general case. Even if `getSkill` is `@Pure`, the following call of `myfunction` could have side effects that would change the result of the next `getSkill` call.

**Comment by svenefftinge** [comment]
I think it's possible, but would be a lot of extra work for limited benefit. Why not using a local variable in that case. Also in future we plan to reduce the amount of synthetic local variables, so there wouldn't be any _skill variables at all.
