### ISSUE TITLE
[J9] Increase ASM version ranges

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#208]
we should possibly use a range of asm versions or switch to asm6 generally

**Comment by cdietrich** [comment]
@szarnekow @svenefftinge what do you think?

**Comment by szarnekow** [comment]
I’m in favor of switching to ASM6.

**Comment by cdietrich** [comment]
Fixed in Xtext 2.14

**Comment by akosyakov** [comment]
In my project proguard is used and it does not support J9 yet: https://sourceforge.net/p/proguard/feature-requests/181/. As a workaround I changed dependencies to use 5.0.1.
