### ISSUE TITLE
generateXbase fails with java.lang.SecurityException

### ISSUE THREAD

**Issue by manuelleduc** [eclipse/xtext-extras#223]
Hello,

I have updated some part of Xtype.xtext
Consequently, I want to regenerate the files derived from the grammar.

I did not found a .mwe2 file, but org.eclipse.xtext.xbase.GenerateXbase is documented in build.gradle as the way to go.

So, I tried to execute it directly in eclipse and to execute it using `./gradlew org.eclipse.xtext.xbase:generateXbase`, always with the same following stacktrace:

 
> :org.eclipse.xtext.common.types:compileJava
> Note: /home/mleduc/git/xtext-extras/org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/reflect/CachingReflectionTypeProvider.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> :org.eclipse.xtext.common.types:processResources NO-SOURCE
> :org.eclipse.xtext.common.types:classes
> :org.eclipse.xtext.common.types:genManifest
> :org.eclipse.xtext.common.types:jar
> :org.eclipse.xtext.ecore:compileJava
> :org.eclipse.xtext.ecore:processResources NO-SOURCE
> :org.eclipse.xtext.ecore:classes
> :org.eclipse.xtext.ecore:genManifest
> :org.eclipse.xtext.ecore:jar
> :org.eclipse.xtext.generator:compileJava
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> :org.eclipse.xtext.generator:processResources UP-TO-DATE
> :org.eclipse.xtext.generator:classes
> :org.eclipse.xtext.generator:genManifest
> :org.eclipse.xtext.generator:jar
> :org.eclipse.xtext.xbase:compileMwe2Java
> :org.eclipse.xtext.xbase:processMwe2Resources NO-SOURCE
> :org.eclipse.xtext.xbase:mwe2Classes
> :org.eclipse.xtext.xbase:processResources
> :org.eclipse.xtext.xbase:generateXbase
> 0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
> 78   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
> 231  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - No project file found for /home/mleduc/git/xtext-extras/org.eclipse.xtext.xbase/build/classes/mwe2. The folder was neither an Eclipse 'bin' folder, nor a Maven 'target/classes' folder.
> 231  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - No project file found for /home/mleduc/git/xtext-extras/org.eclipse.xtext.xbase/build/resources/mwe2. The folder was neither an Eclipse 'bin' folder, nor a Maven 'target/classes' folder.
> 273  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - No project file found for /home/mleduc/git/xtext-extras/org.eclipse.xtext.xbase/build/resources/main. The folder was neither an Eclipse 'bin' folder, nor a Maven 'target/classes' folder.
> 279  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase at 'file:/home/mleduc/git/xtext-extras/org.eclipse.xtext.xbase/'
> 280  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase.ide at 'file:/home/mleduc/git/xtext-extras/org.eclipse.xtext.xbase.ide/'
> 281  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase.ui at 'file:/home/mleduc/git/xtext-eclipse/org.eclipse.xtext.xbase.ui/'
> 301  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
> 807  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 814  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 873  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 874  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
> Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.xtext.generator.IGeneratorFragment"'s signer information does not match signer information of other classes in the same package
>         at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
>         at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
>         at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
>         at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
>         at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
>         at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:950)
>         at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:957)
>         at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:943)
>         at org.eclipse.xtext.xtext.generator.AbstractXtextGeneratorFragment.initialize(AbstractXtextGeneratorFragment.java:45)
>         at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.initialize(CompositeGeneratorFragment2.java:69)
>         at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:285)
>         at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:185)
>         at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:139)
>         at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:21)
>         at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:65)
>         at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:197)
>         at org.eclipse.xtext.xbase.GenerateXbase.main(GenerateXbase.java:193)
> Caused by: java.lang.SecurityException: class "org.eclipse.xtext.generator.IGeneratorFragment"'s signer information does not match signer information of other classes in the same package
>         at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
>         at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at java.lang.Class.getDeclaredFields0(Native Method)
>         at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
>         at java.lang.Class.getDeclaredFields(Class.java:1916)
>         at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:649)
>         at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
>         at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:90)
>         at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
>         at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
>         at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
>         at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
>         at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
>         ... 16 more
> :org.eclipse.xtext.xbase:generateXbase FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':org.eclipse.xtext.xbase:generateXbase'.
> > Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 15.985 secs

How can I avoid this stack. Otherwise what is the correct way to regenerate the project after a modification of the grammars?

Sincerely

Manuel Leduc

**Comment by cdietrich** [comment]
you should be able to call GenerateXbase (java class) from eclipse

it might be that you somehow call a mixture of signed and unsigned stuff

i assume you did not call gradle with `-PuseJenkinsSnapshots=true` as arg so the stuff from sonatype oss might have been used

you might have to add `--refresh-dependencies` too to make sure caches are not used / dependencies are refreshed

**Comment by cdietrich** [comment]
@manuelleduc  any feedback on my remarks?

**Comment by manuelleduc** [comment]
Sadly, it did no fix the issue. 

Below, a summary of how I proceded this time.

So I cloned a clean version of xtext-extras (just to be sure).
Build it with `./gradlew clean cleanGenerateXtext build -PcompileXtend=true  -PignoreTestFailures=true -PuseJenkinsSnapshots=true --refresh-dependencies --continue`
Imported it into a Eclipse IDE for Java and DSL Developers Photon using Import -> Import Existing Project.

A this point when executing GenerateXbase in eclipse, I got an error telling that `org.eclipse.xtext.xbase.ui` was missing.
So I cloned xtext-eclipse (next to xtext-extras, since the uiProject variable seems to contains a relative path) and imported its project into the workspace.


Once done, running again GenerateXbase lead to the previous error:


> 0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
> 116  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
> 585  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase at 'file:/tmp/xtext-extras/org.eclipse.xtext.xbase/'
> 586  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase.ide at 'file:/tmp/xtext-extras/org.eclipse.xtext.xbase.ide/'
> 586  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.eclipse.xtext.xbase.ui at 'file:/tmp/xtext-eclipse/org.eclipse.xtext.xbase.ui/'
> 627  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
> 1336 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 1353 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 1381 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
> 1381 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
> Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.xtext.generator.IGeneratorFragment"'s signer information does not match signer information of other classes in the same package
> 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
> 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
> 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
> 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
> 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
> 	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:950)
> 	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:957)
> 	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:943)
> 	at org.eclipse.xtext.xtext.generator.AbstractXtextGeneratorFragment.initialize(AbstractXtextGeneratorFragment.java:45)
> 	at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.initialize(CompositeGeneratorFragment2.java:69)
> 	at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:285)
> 	at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:185)
> 	at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:139)
> 	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:21)
> 	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:65)
> 	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:197)
> 	at org.eclipse.xtext.xbase.GenerateXbase.main(GenerateXbase.java:193)
> Caused by: java.lang.SecurityException: class "org.eclipse.xtext.generator.IGeneratorFragment"'s signer information does not match signer information of other classes in the same package
> 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
> 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.getDeclaredFields0(Native Method)
> 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
> 	at java.lang.Class.getDeclaredFields(Class.java:1916)
> 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:649)
> 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
> 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:90)
> 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
> 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
> 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
> 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
> 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
> 	... 16 more

**Comment by cdietrich** [comment]
Did you delete gradle caches at ~/.gradle ?

**Comment by cdietrich** [comment]
How do the dependencies from the project look like in eclipse ?

**Comment by cdietrich** [comment]
still cannot reproduce

```
cd tmp
mkdir .gradle
export GRADLE_USER_HOME=/home/dietrich/tmp/.gradle
git clone https://github.com/eclipse/xtext-extras.git
git clone https://github.com/eclipse/xtext-eclipse.git
cd xtext-extras
./gradlew clean cleanGenerateXtext build -PcompileXtend=true -PignoreTestFailures=true -PuseJenkinsSnapshots=true --refresh-dependencies --continue
./gradlew org.eclipse.xtext.xbase:generateXbase -PuseJenkinsSnapshots=true
```

**Comment by manuelleduc** [comment]
Using this method, I managed to build the Xbase grammar.

Thanks a lot for the advices.

Another slightly off topic question, is their a way to shorten the build time? The first gradle call is taking 21 minutes to finish on my laptop (or is this first gradle call required only once?).

**Comment by cdietrich** [comment]
dont do -PcompileXtend=true cleanGenerateXtext
dont do javadoc and tests

=>

```
./gradlew clean build -PignoreTestFailures=true -PuseJenkinsSnapshots=true --refresh-dependencies --continue -x test -x javadoc
```

**Comment by manuelleduc** [comment]
Faster indeed, the execution time goes from 22 minutes to 45 seconds.

Thanks again.

I guess this issue can be closed :)
