### ISSUE TITLE
Decide how to deal with dependency to jsr305 in tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#23]
with 1707a99ffdea804389a0c3690804a44ec1fd8d4b we exclude jsr 305 from tests since the test expectations expect it not to be there explicitely. when https://github.com/TypeFox/ls-api/issues/31 is decided upon we have to decide how to deal with that here (keep 1707a99ffdea804389a0c3690804a44ec1fd8d4b, undo 1707a99ffdea804389a0c3690804a44ec1fd8d4b, adapt test expectations and undo 1707a99ffdea804389a0c3690804a44ec1fd8d4b

**Comment by spoenemann** [comment]
I think the current solution is ok.
