### ISSUE TITLE
Introducing overriding mechanism for cast operator.

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-extras#236]
In [this discussion](https://www.eclipse.org/forums/index.php/m/1782935/), I have proposed the idea to introduce a mechanism for overriding the cast operator.

In Xbase DSL, we have the cast operator, e.g. `value as type`.
In Java, we have functions for converting an object to another type, e.g. `toString()`.

A mechanism may automatically link the cast operator within a DSL to any "toX" function.

Let the DSL code `value as Type`

The DSL compiler should try:
* If the type of the value is a primitive type, use the standard cast operator;
* If the type of the value is a super type of Type, use the standard cast operator; 
* If a single function `def toXYZ : Type` is defined within the type of value (name of the function must start with "to" and the return type is tested, i.e. "XYZ" is not tested), call it;
* If a single function `def toXYZ : T` where "T is a sub type of Type" is defined, call it;
* Otherwise, use the standard cast operator.

**Comment by kthoms** [comment]
@szarnekow @cdietrich WDYT?
I like the idea.

**Comment by szarnekow** [comment]
Casts have a special semantics in Java. What is the benefit of having two additional spaces compared to the default way of calling `toString`, `toType` or `toSomething`?

**Comment by cdietrich** [comment]
i am not sure if we are able to generally determine the correct method. or if every api offers a X.toY method that can be considered as a "cast" or "conversion".

**Comment by gallandarakhneorg** [comment]
According to my discussions with  the users of my DSL, who do not really know and care about the semantics of Java and other object-oriented languages, the "as" operator enables to change a value to another type. As they are newbies in computer science they do not see a difference between casting (no copy of the value) and converting (copy to another value) since it is a typical computer science problem. They do not understand why they cannot override the "as" operator as for the other operators. And, it hard to explain without explaining Java semantic.
This point of view is shared by the C++ community in which the cast operator could be overridden.

Nevertheless, by general algorithm above may cover all the cases, and a warning should be output to the DSL developer when "conversion" is used.

I have proposed to link the cast operator to the "toX" function because the naming conversion is known within Java community. Using "operator_cast" name for the function is consistent with the rest of the Xbase API, but annoying when using an existing Java libraries.

**Comment by szarnekow** [comment]
For Xtend and Xbase in particular, it is important to stay rather close to Java. Reading your reasoning, I suspect that this should be implemented specifically for your DSL. For the average case, the understanding of object identity and conversion and the differences between both, is valuable and should not be disguised.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
