### ISSUE TITLE
JvmModelAssociator performance tweak

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-extras#238]
AFAICT there is no reason why the `JvmModelAssociator`'s `sourceToTargetMap` has to contain ordered Set values. So in the code of `associatePrimary()` below:

https://github.com/eclipse/xtext-extras/blob/1e7729d30fbfd3b58d34b1317c740c9c0d6d825e/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java#L279

it should be possible to pass `false` instead of `true` as the last argument (or directly call the corresponding overloaded method).

Optionally the Map could even contain "plain" `HashSet` values instead of the custom `ListBasedSet` objects. The performance would be better when associating many inferred elements with the same source element (ListBasedSet#add() has linear complexity), but the memory consumption would be higher (haven't computed or measured the actual difference).

**Comment by cdietrich** [comment]
hello knut, did you have a look at the resource storage facade? and uris that might change. 
see `org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeAssociationsAdapter(BatchLinkableResource, OutputStream)`

if a simple map is used with undefined order you will get errors like this one after reading: 
https://github.com/eclipse/xtext-extras/issues/27

**Comment by knutwannheden** [comment]
Hi Christian,

Yes, I am aware of the resource storage facade. As pointed out, I think for the `sourceToTargetMap` the order doesn't need to be maintained; `getPrimaryJvmElement()` only relies on the order of `targetToSourceMap`. But maybe I missed something.

**Comment by cdietrich** [comment]
but calling getPrimarySourceElement does rely on that. and if you have structures that work on the inferred model and allow navigation to the original model (wo do that in our project) this will break.

**Comment by knutwannheden** [comment]
I just noticed that `getPrimaryJvmElement()` and `isPrimaryJvmElement()` rely on the order of `sourceToTargetMap`. Somehow missed that before.

**Comment by knutwannheden** [comment]
(In our own JVM-independent adaptation of `IJvmModelAssociations` we only provide `getPrimarySource()` and no `getPrimaryInferredElement()`).
