### ISSUE TITLE
Develop a concept to support "new" features with xbase

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#244]
Develop a concept to support "new" features like try with resources, try multi catch, more number literals and operators with xbase with or without breaking clients e.g. by introducing a new subgrammar similar to XbaseWith Annotations

**Comment by szarnekow** [comment]
Hi @loradd that's an unfortunate overlap since we do already have this first draft of the implementation locally. Maybe you want to share your solution so we can discuss how to join forces, though.

**Comment by loradd** [comment]
Hi @szarnekow, sure! 

I have first defined a new `XTernaryIfExpression` rule "between" `XExpression` and `XAssignment` in ` org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/Xbase.xtext`, as follows:

    XExpression returns XExpression:
        XTernaryIfExpression
    ;

    XTernaryIfExpression returns XExpression:
        XAssignment =>({XIfExpression.if = current} '?' 
            then=XExpression (=>':' else=XExpression)?
        )?

Then, I changed the `XBaseSemanticSequencer` managing ternary expressions as ordinary if expressions in `org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/XbaseSemanticSequencer.java`, as follows:
    
    @Override
    protected void sequence_XIfExpression_XTernaryIfExpression(ISerializationContext context, XIfExpression semanticObject) {
        super.sequence_XIfExpression(context, semanticObject);
    }

**Comment by loradd** [comment]
Yes, thank you!

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
