### ISSUE TITLE
BatchLinkableResourceStorageLoadable/Writable loose order of AssociationsAdapter

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#27]
a `BatchLinkableResource` serialized with  `BatchLinkableResourceStorageWritable` and read again with `BatchLinkableResourceStorageLoadable` (as it is done by `BatchLinkableResourceStorageFacade`) looses the order of the maps and the set entries inside the map for AssociationsAdapter.

thus using `IJvmModelAssociations.getPrimaryJvmElement(EObject)` etc. on a loaded resource leads to unpredictable behaviour

**Comment by cdietrich** [comment]
@svenefftinge was it intended to use simply hashmaps and hashsets there or did it just get lost that these are ordered?

**Comment by cdietrich** [comment]
It happen only when enabling node model serialization

**Comment by cdietrich** [comment]
@svenefftinge any feedback on this one?

**Comment by svenefftinge** [comment]
No it wasn't intended, we should change them to Linked* ones.

**Comment by cdietrich** [comment]
ok ill provide a pull req

**Comment by cdietrich** [comment]
Fixed in Xtext 2.11
