### ISSUE TITLE
Investigate Failing Tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#289]
http://services.typefox.io/open-source/jenkins/job/xtext-extras/job/master/387/testReport/

@gallandarakhneorg is this related to your changes?

**Comment by gallandarakhneorg** [comment]
I will investigate since the project compile on my laptop.

**Comment by cdietrich** [comment]
i have already restored a method in MapExtensions you may have accidentally removed.

**Comment by gallandarakhneorg** [comment]
@cdietrich thx. Indeed, I have failed to detect this code removal before pushing my PR.
