### ISSUE TITLE
Extract relevant tests from xtext.tests

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-extras#3]
See eclipse/xtext-core#2 and eclipse/xtext-core#3: After the tests in org.eclipse.xtext.tests have been fixed for xtext-core, those relevant for xtext-extras should be extracted (e.g. old generator tests).

**Comment by cdietrich** [comment]
closed with https://github.com/eclipse/xtext-extras/commit/bd0ad97418e783bcf4a01adeeed0ad24f7e0c077
