### ISSUE TITLE
Invalid primitive boolean conformity.

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-extras#313]
Let the following unit test code:
```java
public class PrimitiveBooleanComparison extends AbstractXbaseTestCase {

	private static final String SNIPSET1 = "{ true }";

	@Inject
	private TypeReferences typeReferences;

	@Inject
	private CommonTypeComputationServices services;

	@Test
	public void isSubtypeOf_00() throws Exception {
		XExpression code0 = expression(SNIPSET1, false);
		XExpression code1 = expression(SNIPSET1, false);

		JvmTypeReference reference0 = this.typeReferences.getTypeForName("boolean", code0);
		
		StandardTypeReferenceOwner owner = new StandardTypeReferenceOwner(this.services, code1);
		LightweightTypeReference reference1 = owner.newParameterizedTypeReference(this.typeReferences.findDeclaredType("boolean", code1));
		
		assertTrue(reference1.isSubtypeOf(reference0.getType()));
	}

	@Test
	public void isAssignableFrom_00() throws Exception {
		XExpression code0 = expression(SNIPSET1, false);
		XExpression code1 = expression(SNIPSET1, false);

		JvmTypeReference reference0 = this.typeReferences.getTypeForName("boolean", code0);
		
		StandardTypeReferenceOwner owner = new StandardTypeReferenceOwner(this.services, code1);
		LightweightTypeReference reference1 = owner.newParameterizedTypeReference(this.typeReferences.findDeclaredType("boolean", code1));
		
		assertTrue(reference1.isAssignableFrom(reference0.getType()));
	}
}
```

This code is testing if a type reference to the primitive "boolean" is a subtype of another type reference to the same primitive type.
The first type reference is a `JvmTypeReference`. The second is a `LightweightTypeReference`.

_Surprisingly, the tests are failing._

This behavior causes the `IResolvedOperation` failing that is used for checking the validiting of the return types of the functions in my DSL. It is one cause of the [Issue 49 of xtext-lib](https://github.com/eclipse/xtext-lib/issues/49).

**Comment by szarnekow** [comment]
You test seems to use different resource sets. Can you please add an assertion that checks that all the objects come from the same resource set?

**Comment by gallandarakhneorg** [comment]
I confirm they are not in the same resource sets.

I understand that the resource sets provide contexts (the bounds) for type resolution. 
So, according to this fact, this issue could be close.

But, the existing of different resource sets may be a cause of the [Issue 49 of xtext-lib](https://github.com/eclipse/xtext/issues/2242).
