### ISSUE TITLE
Add option to pass command line parameters to compiler

### ISSUE THREAD

**Issue by rosczja** [eclipse/xtext-extras#372]
I would like to add a get/set method for command line parameters to the CompilerConfiguration class. In that way additional parameters could be passed to the underlying compiler.

This would also help with issue https://github.com/eclipse/xtext-maven/issues/23

**Comment by ArneDeutsch** [comment]
`CompilerConfiguration` is used in `EclipseJavaCompiler` (https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/EclipseJavaCompiler.java). I think in this case the eclipse java compiler is called but in other circumstances `javac`might be called. At least the interface `IJavaCompiler` is general enough to support this. As `CompilerConfiguration` is part of this interface I would reason that supporting specific parameters (as already done with `sourceLevel`, `targetLevel` and `verbose`) would be preferable to support multiple compilers. Would that work for your case as well? Have the feeling that if we allow to pass any parameter the user is tying itself to one compiler and hence might run into issues later on.

**Comment by rosczja** [comment]
Does the user not have to explicitly choose a compiler if he is not happy with the default? I think one can assume that in that case the user should be aware which compiler args are valid for the chosen compiler.

I need the following two arguments:
-parameters
-proc:none

For both I could think of specific parameters. But then in the future someone else needs another special parameter and than do you want to again add a special parameter?

**Comment by cdietrich** [comment]
Show be fixed in 2.17
