### ISSUE TITLE
ideaPlugin in PureXbase mwe2 Workflow causes error

### ISSUE THREAD

**Issue by epoell** [eclipse/xtext-extras#392]
In the PureXbase mwe2 Workflow (`/org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/GeneratePureXbase.mwe2`) the ideaPlugin is still listed. If the workflow is run, an error is thrown:
> ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow org.eclipse.xtext.purexbase.PureXbase:
> The project's path '../../xtext-idea/org.eclipse.xtext.purexbase.idea' does not exist
java.lang.RuntimeException: Problems running workflow org.eclipse.xtext.purexbase.PureXbase: The project's path '../../xtext-idea/org.eclipse.xtext.purexbase.idea' does not exist

The error is avoided by commenting out the lines abut the ideaPlugin (ll. 24-27).

**Comment by cdietrich** [comment]
put this on the list for abandoning idea completely

**Comment by cdietrich** [comment]
@holgerschill is this fixed now by the removal of xtext-idea?

**Comment by holgerschill** [comment]
Yes.
