### ISSUE TITLE
EqualsWithNullTest fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#408]
```
org.junit.ComparisonFailure: expected:<['=='
'===']> but was:<[Expected WARNING 'org.eclipse.xtext.xbase.validation.IssueCodes.equals_with_null' on XBinaryOperation at [-1:-1] but got
ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Syntax) 'mismatched input '<EOF>' expecting '}'' on XNullLiteral, offset 25, length 4
]>
```

@szarnekow any idea?

**Comment by cdietrich** [comment]
i also wonder why i dont see the failure here: https://jenkins.eclipse.org/xtext/job/xtext-extras/job/master/

**Comment by cdietrich** [comment]
seems to be related to injector provider changes

**Comment by cdietrich** [comment]
previously 

[ERROR:mismatched input '<EOF>' expecting '}' (__synthetic0.___xbase line : 1 column : 26), WARNING:The operator '==' should be replaced by '===' when null is one of the arguments. (__synthetic0.___xbase line : 1 column : 24)]

now only the first one

**Comment by cdietrich** [comment]
can be reproduce with greeting sample too.
we need to regenerate all langs again

**Comment by szarnekow** [comment]
Fixed
