### ISSUE TITLE
[XbaseValidator] NPE in checkCasts

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-extras#50]
I just faced a NPE while editing Xtend code:
```
Thread [Worker-50] (Suspended (exception NullPointerException))	
	owns: Object  (id=1091)	
	StandardTypeReferenceOwner.<init>(CommonTypeComputationServices, EObject) line: 42	
	XtendValidator(XbaseValidator).toLightweightTypeReference(JvmTypeReference, boolean) line: 387	
	XtendValidator(XbaseValidator).toLightweightTypeReference(JvmTypeReference) line: 383	
	XtendValidator(XbaseValidator).checkCasts(XCastedExpression) line: 822	
	...
```

The context was while editing a cast expression which is not complete yet:
```
(model.declarations.head as 
```

In this case `context` is null. Going back in the stack to XbaseValidator#checkCasts it shows that cast#type is null. This could be guarded.

The issue is low severity since exceptions are catched anyway, but if NPEs are not thrown while debugging this would be nicer.

**Comment by cdietrich** [comment]
Fixed with xtext 2.11
