### ISSUE TITLE
xtext-extras compilation fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#544]
09:16:53  > Task :org.eclipse.xtext.java:compileJava FAILED
09:16:53  /home/jenkins/agent/workspace/xtext-extras_master/org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java:85: error: incompatible types: missing return value
09:16:53        return;
09:16:53        ^
09:16:53  Note: Some input files use unchecked or unsafe operations.
09:16:53  Note: Recompile with -Xlint:unchecked for details.
09:16:53  1 error

**Comment by cdietrich** [comment]
code infers   

public Object discardDerivedState(final Resource resource) {

for some reason

**Comment by cdietrich** [comment]
i have no idea what has changed to cause this.

**Comment by szarnekow** [comment]
It should probably be a warning in our codebase when we use inferred return types. To be investigated though what caused this change.

**Comment by cdietrich** [comment]
After restarting core it’s green again

**Comment by cdietrich** [comment]
def discardDerivedState(Resource resource) {

vs

org.eclipse.xtext.resource.IDerivedStateComputer.discardDerivedState(DerivedStateAwareResource)

something is totally wrong here

any idea @szarnekow

**Comment by cdietrich** [comment]
saw this today again. also on different machines. in eclipse (hover) and gradle

**Comment by cdietrich** [comment]
will move to 2.22

**Comment by cdietrich** [comment]
will close this as wont fix
