### ISSUE TITLE
Late JvmMember initialization not working

### ISSUE THREAD

**Issue by rosczja** [eclipse/xtext-extras#555]
I noticed that in the class `JvmModelAssociator` while installing derived state the JvmMember initialization runnable is always immediately run, line 404 - 408.

This is because `lateJvmMemberInit` is always false, even if I use a `BatchLinkableResource`.

Looking into `BatchLinkableResource` I can see that the variable `hasJvmMemberInitializers` is set to `true` when the method `addJvmMemberInitializer` is called.

The only caller of that method I could find is the class `JvmModelAssociator` and the problem is that this class calls this method before calling the `addJvmMemberInitializer` method. In this case the `hasJvmMemberInitializers` method always returns `false`.

Is this the intented behaviour or am I missing something?

**Comment by cdietrich** [comment]
@szarnekow any idea?

**Comment by szarnekow** [comment]
Can you please share a piece of code that illustrates the problem? A unit test or something? Ideally it would be based on something from `org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel`

**Comment by rosczja** [comment]
Yes I could try. But I think it would be easier, if this is okay, to just open a Xbase based DSL in Eclipse and set a break point in the `installDerivedState` method of the class `JvmModelAssociator`. This will immediately show that `lateJvmMemberInit` is always false.

**Comment by szarnekow** [comment]
@rosczja in order to defer the member initialization even further, the model inferrer must explicitly use `BatchLinkableResource.addJvmMemberInitializer(Runnable)`, so seeing the flag `lateJvmMemberInit` being false for arbitrary languages is expected.

**Comment by rosczja** [comment]
@szarnekow Hm, not sure if I totally agree with that, but okay. I looked into the Xtend inferrer source code and what happens there (active annotation processing aside) is that instead of passing the initializer runnable as a parameter to the acceptor and letting the acceptor take care of late initialization, it is explicitly added to the BatchLinkableResource.

I find this not very intuitive and I would think that if an arbitray language choose to use `BatchLinkableResource` it should also get the late member initialization for free.

**Comment by szarnekow** [comment]
I'm not arguing against that. Just saying, that the code currently works as designed (tm). We could possibly adjust that, though. Would you be willing to submit a patch? It will likely need a couple of iterations in the review, I'm afraid.

**Comment by rosczja** [comment]
@szarnekow I like works as designed (tm) ;-) I will think about something if I find some spare time.
