### ISSUE TITLE
[refactoring] Migrate Xbase Testlanguages to new generator

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-extras#57]
The workflow GenerateXbaseTestLanguages.mwe2 uses the old generator infrastructure and should be refactored to the new generator.

This will affect the produced sources in org.eclipse.xtext.xbase.testlanguages and org.eclipse.xtext.xbase.testlanguages.ui. Usually this would also imply new projects
- org.eclipse.xtext.xbase.testlanguages.ide
- org.eclipse.xtext.xbase.testlanguages.tests
- org.eclipse.xtext.xbase.testlanguages.ui.tests
  but for simplicity the generated sources could also be put into the both existing projects.

The UI project `org.eclipse.xtext.xbase.testlanguages.ui` is contained in the repository xtext-eclipse, thus the generator has to produce code to the other repo location. It should be assumed that it resides in "xtext-eclipse.git" as it would be checked out by Oomph.

**Comment by spoenemann** [comment]
Corresponding PR: #58

**Comment by cdietrich** [comment]
migrated: 
- org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/tests/GenerateBuilderTestLanguages.mwe2
- /org.eclipse.xtext.common.types.tests/src/org/eclipse/xtext/common/types/xtext/ui/CommonTestLanguagesFragments.mwe2 
- /org.eclipse.xtext.common.types.tests/src/org/eclipse/xtext/common/types/xtext/ui/GenerateTypesTestLanguages.mwe2
- /org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/enumrules/GenerateEnumRuleTestLanguage.mwe2
- /org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/generator/grammarAccess/GenerateGrammarAccessTestLanguage.mwe2
- /org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/GenerateAllTestLanguages.mwe2
- /org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/TestLanguagesFragments.mwe2
- /org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2

@kthoms @spoenemann is there anything missing?

missing:

**Comment by spoenemann** [comment]
I think it's good now. You can generate _all_ test languages by running
```
./gradlew generateTestLanguages
```

**Comment by cdietrich** [comment]
regenerating gives no changes => will close this issue
