### ISSUE TITLE
Xbase serializer tests are broken in master

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-extras#63]
While working on Xbase issues, I noted that some Xbase serializer tests are broken in master, see 

http://services.typefox.io/open-source/jenkins/job/xtext-extras/job/master/lastCompletedBuild/testReport/

The problematic commit, which comes from xtext-core, is this one https://github.com/eclipse/xtext-core/pull/129/commits/cb9981d14cc279cb0433b63c9c88f8ebf20ba739 which was merged as part of https://github.com/eclipse/xtext-core/pull/129

@meysholdt could you please have a look?

One of the failing test fails due to wrong expectation, but there are also two tests failing with a NPE

**Comment by meysholdt** [comment]
will do
