### ISSUE TITLE
[Formatter] Xtext generates a broken link.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-extras#70]
Xtext generates a broken link {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} within the <MyDsl>Formatter.java class.
![formatter_broken_link](https://cloud.githubusercontent.com/assets/20393472/20090738/43a968d8-a58f-11e6-9aad-7fad7fc9a5b9.png)
xtext-extras/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/formatting/FormatterFragment.xpt

**Comment by cdietrich** [comment]
Fixed in Xtext 2.11
