### ISSUE TITLE
[compiler] Treat "object != null" like "object !== null"

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-extras#72]
The code produced for `object !== null` is slightly more efficient than `object != null`. Users are not aware of the fact and will usually use the `!=` operator, since they are just used to it. Xbase produced `(!Objects.equal(_object, null))` from it, while using the `!==` operator would compare the objects directly.

The compiler should produce the same output and avoid the call of Objects.equal when one operator is the null literal.

**Comment by cdietrich** [comment]
same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=420983

**Comment by kthoms** [comment]
You are right, this one can be closed.

**Comment by cdietrich** [comment]
btw did you see the warning on this in 2.11?

**Comment by kthoms** [comment]
I didn't see the warning, but the nonsense generated code.
