### ISSUE TITLE
Avoid empty lines with two spaces between members

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-extras#772]
Currently, the JvmModelGenerator separates each generated member with an empty line, which is OK!
However, due to the indentation of the appendable, these empty lines have two spaces, see e.g., the generated Java code from a Domainmodel file:

![image](https://user-images.githubusercontent.com/1202254/161913220-591c8a93-2b71-44ac-8204-c6674a324f65.png)

In general, this is not a problem (though those two spaces are useless and you wouldn't put them in the manually written Java; at least, I never do). However, if you use Java TextBlocks to compare the generated code with some expectations (typically making a JUnit test fail, and copying the actual code from the comparison dialog), you'll get failures. In fact, Java TextBlocks strip trailing spaces, and this holds for lines with only spaces.

For example, take this Java 17 test:

```java
package org.eclipse.xtext.example.domainmodel.tests;

import static org.junit.Assert.assertEquals;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.xbase.testing.CompilationTestHelper;
import org.eclipse.xtext.xbase.testing.TemporaryFolder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.inject.Inject;

@RunWith(XtextRunner.class)
@InjectWith(DomainmodelInjectorProvider.class)
public class DomainmodelCompilerTest {

	@Rule
	@Inject
	public TemporaryFolder temporaryFolder;

	@Inject
	private CompilationTestHelper compilationTestHelper;

	@Test
	public void compareGeneratedJava() throws Exception {
		compilationTestHelper.compile("""
			entity Foo {
				name : String
			}
			""", it -> {
			assertEquals("""
			import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
			import org.eclipse.xtext.xbase.lib.util.ToStringBuilder;
			
			@SuppressWarnings("all")
			public class Foo {
			  public Foo() {
			  }
			  
			  public Foo(final Procedure1<Foo> initializer) {
			    initializer.apply(this);
			  }
			  
			  private String name;
			  
			  public String getName() {
			    return this.name;
			  }
			  
			  public void setName(final String name) {
			    this.name = name;
			  }
			  
			  @Override
			  public String toString() {
			    String result = new ToStringBuilder(this).addAllFields().toString();
			    return result;
			  }
			}
			"""
			, it.getSingleGeneratedCode());
		});
	}
}
```

This fails as follows:

![image](https://user-images.githubusercontent.com/1202254/161914715-bc225bd6-266e-4057-81b2-30e4cbc92db8.png)

which is misleading, because we put the empty lines with two spaces in the expectation, but Java strips it (see the screenshot that highlights the spaces are present):

![image](https://user-images.githubusercontent.com/1202254/161914941-4961be55-9314-4169-8156-04ddd889132a.png)

One can force Java to take those two spaces into consideration with `\s` (note, one space, and then `\s` will tell Java to consider all the trailing spaces, including the space character `\s`); for example, now the test succeeds

![image](https://user-images.githubusercontent.com/1202254/161915978-4d9be376-1099-42e5-ae82-18967030a5b8.png)

But this is not ideal for the developer, who'll have to always post-process manually the pasted textblock.

In my case, I remove from the generated text file those empty lines, e.g.,

```java
	private void assertGeneratedJavaCode(CompilationTestHelper.Result r, CharSequence expected) {
		assertEquals(expected.toString(),
			// lines with only spaces are skipped in Java text blocks
			// but they are present in the generated code so we need to remove them
			r.getSingleGeneratedCode().replace("  \n", "\n"));
	}
```

However, this requires additional effort, just for those two spaces, which shouldn't even be there...
For sure, it might be misleading to those who want to start using Java textblocks for tests.

Do you think it might be a good idea to change the JvmModelGenerator behavior in that respect? From what I understand, it should be a matter of removing the indentation before adding the separating newline and then adding the indentation back.

For sure, it will require updating several tests.

**Comment by szarnekow** [comment]
> Do you think it might be a good idea to change the JvmModelGenerator behavior in that respect?

Yes, I think so. Would you be willing to work on this?

**Comment by LorenzoBettini** [comment]
Yes, I'll try that as soon as possible.
Concerning textblocks there's also the problem of line endings (in textblocks are ALWAYS just `\n`, while Xtend uses System's line separator, if I'm not wrong, so in Windows the output will be different). But dealing with `\r` is not a big deal; it's just a replace("\r", "") ;)

**Comment by LorenzoBettini** [comment]
@szarnekow, I started to work on that; I see no Xbase test failing (though, with debugging, I can see that the two spaces are not generated anymore). Can you please confirm that JvmModelGenerator has no test verifying the generated output? Maybe I should use Xtend tests?

**Comment by cdietrich** [comment]
simply create same named branch in  xtext-xtend and push it once extras branch is built

**Comment by LorenzoBettini** [comment]
@cdietrich, nothing else to do? It works automagically?

I also wanted to be sure that Xbase tests themselves do not verify the output of the JvmModelGenerator.

**Comment by cdietrich** [comment]
i have no clue how many tests we have in extras. in doubt few

**Comment by szarnekow** [comment]
@LorenzoBettini I think we want to add two methods `ITreeAppendable.blankLine()` and `ITreeAppendable.blankLines(int count)` which would call something like `state.appendNewLine(this);` on the internal state object of the TreeAppendable and only append the indentation after having added the correct number of newlines.

**Comment by LorenzoBettini** [comment]
@szarnekow if you look at my last commit https://github.com/eclipse/xtext-extras/commit/5ae61c90d11709ac21d6e93a16e0d55d18da28b2 you can call several times blankLines. Currently only once is enough. I'm testing this with Xtend, since as I said above, there's no test in Xbase for that.

**Comment by cdietrich** [comment]
@LorenzoBettini miss PRs for web and eclipse

**Comment by LorenzoBettini** [comment]
@cdietrich working on that...

**Comment by LorenzoBettini** [comment]
@cdietrich If I understand correctly "web" does not store xtend-gen in the Git repository, so for that there's nothing to do

**Comment by cdietrich** [comment]
ok

**Comment by LorenzoBettini** [comment]
@cdietrich everything done now!

**Comment by cdietrich** [comment]
thx
