### ISSUE TITLE
Since Java 15: Unable to reference Java types in the same project

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-extras#792]
Starting with Java 15 referencing Java types which are located in the same project as the DSL doesn't work anymore.

I created a repository containing a sample language and a concrete model using that language to demonstrate the issue: https://github.com/OLibutzki/HelloJava

There also is a [GitHub Actions Matrix Build](https://github.com/OLibutzki/HelloJava/actions/runs/2656339113) which shows that this seems to be broken starting with Java 15.

I am aware of https://github.com/eclipse/xtext/issues/1982, but it's quite hard to extract, if this issue is covered somewhere.

**Comment by cdietrich** [comment]
see 
https://github.com/OLibutzki/HelloJava/blob/e3b443496d6f42e72edb5fab794afa44d6964442/language/pom.xml#L101
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/148
https://github.com/eclipse/xsemantics/issues/158

can you build with -X

**Comment by cdietrich** [comment]
besides that xtext does NOT support
[INFO] Compiler source level: 15
[INFO] Compiler target level: 15

**Comment by OLibutzki** [comment]
> can you build with -X

Yes, here are the results: https://github.com/OLibutzki/HelloJava/actions/runs/2656549071

> likely this wont work for any non 8,11,17 version
Yes, the LTS versions are sufficient.

Is the referenced WIP not part of 2.28.0.M1 which I use in my project?

**Comment by cdietrich** [comment]
no, as i am currently basically alone with zero motivation
it will take much longer for it to be done

> [WARNING] source level should be in '1.1'...'1.8','9'...'14' (or '5.0'..'14.0'): 17

**Comment by cdietrich** [comment]
i assume 14 is the latest version supported by
https://github.com/eclipse/xtext-lib/blob/1ceac635a8f491ae62a17e5a6f17d400d54438be/org.eclipse.xtext.dev-bom/build.gradle#L36

**Comment by OLibutzki** [comment]
Ok, thanks for helping that quickly, @cdietrich.

**Comment by OLibutzki** [comment]
@cdietrich, I have tested the latest 2.29.0-SNAPSHOTS with my example repo as you stated in https://github.com/eclipse/xtext/issues/1982#issuecomment-1228737605.

You can find the results here: https://github.com/OLibutzki/HelloJava/actions

After switching to the latest Snapshots the builds for Java 15 to 17 passed. The only thing I did was including the snapshot repositories and using 2.29.0-SNAPSHOT as you can see in https://github.com/OLibutzki/HelloJava/commit/6b92ecad60f82466fb0489bf971a053918082d26.

Thanks for your efforts.

**Comment by nils-christian** [comment]
Hello @cdietrich and Hello @OLibutzki,

I might be mistaken here, but is it possible that this broke again? I forked Olivers example and updated it to 2.29.0.M1 (this was released a week ago, so I would assume that it would contain whatever fixed the issue). With said version the build breaks: https://github.com/nils-christian/HelloJava/actions/runs/3217240308/jobs/5259981216

Best regards

  Nils

**Comment by cdietrich** [comment]
the branch has nothing todo with M1, as i dont get sufficient feedback i am hesitant to merge to to master so that it gets onto m1 (or any other milestone)

**Comment by cdietrich** [comment]
Xtext 2.29 for Java 17 is released
