### ISSUE TITLE
add gradle solution for longrunning xbase tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#8]

**Comment by spoenemann** [comment]
What do you mean? Should they be executed with a separate task instead of the standard `test` task?

**Comment by cdietrich** [comment]
"before" we had different jobs for different tests

**Comment by spoenemann** [comment]
Yes, that can be realized by defining a new Gradle task, e.g. `longRunningTest`. Currently the build time for xtext-extras on the server is 9 min 53 sec. Do we really need to extract the long-running tests? I think the build time is already ok. Locally you can use launch configs to trigger different kinds of tests.

**Comment by spoenemann** [comment]
Closing this for now. If someone feels the current default build time is too long, feel free to reopen.
