### ISSUE TITLE
Xbase languages do not correctly track imported names

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-extras#803]
The ImportedNamesAdapter is not correctly installed for some default Xbase language configurations (e.g. if XImportSections are being used).

Also there is no tracking of transitive dependency changes, e.g. if the hierarchy of a referenced type was changed.

**Comment by szarnekow** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=483760

**Comment by cdietrich** [comment]
@szarnekow anything left?

**Comment by szarnekow** [comment]
I consider this to be fixed.
