### ISSUE TITLE
Support incremental builds via the StandaloneBuilder

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-extras#805]
The StandaloneBuilder does always perform a full build. Alternatively it should be able to detect file changes and perform an incremental build instead, similar to what happens in the IDE.

The incremental build shall be exposed to the xtext-maven-plugin.

**Comment by cdietrich** [comment]
@szarnekow any update here?

**Comment by szarnekow** [comment]
> @szarnekow any update here?

I'm doing a round of optimizations and the documentation (n&n) is missing.

**Comment by szarnekow** [comment]
Done.
