### ISSUE TITLE
Introduce possibility to evaluate xbase expressions during debugging

### ISSUE THREAD

**Issue by holgerschill** [eclipse/xtext-extras#95]
As discussed in https://github.com/eclipse/xtext-extras/pull/91 we should think about having support to evaluate expressions like it is done in JDT for Java. I don't have a feeling if this is possible but did not hear something about showstoppers. Of course this is nothing for the upcoming release 2.11.

**Comment by svenefftinge** [comment]
This possible with Java already. Also the extensibility of JDT is relatively limited here, which is why I would say, lets not do it. It would be eclipse specific too.

**Comment by trancexpress** [comment]
Debugging code which uses chaining is very without this. It would be great if Eclipse supports inspection of expressions in xtend/xtext sources. Or at least if the Display View / Debugger Console allows evaluation of these expressions.

As it stands developers must debug the generated code with standard Java tooling. Switching back and forth in that scenario doesn't feel too great.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
